### ISSUE TITLE
Oregon 

### ISSUE THREAD

**Issue by h3xxya** [HelloKitty/AmericansStopSoros#4]
Sorry, I don't have time to figure3 out github before I go to work

Here is some additional Oregon info:

Email addresses for most Oregon county election boards (please complete) and ktvz/zolo media:

countyclerk@shermancounty.net,
clerk@co.tillamook.or.us,
elections@umatillacounty.net,
rchurch@union-county.org,
lindab@co.wasco.or.us,
elections@co.washington.or.us,
bsitton@co.wheeler.or.us,
elections@co.yamhill.or.us,
elections.customer@co.lane.or.us,
djenkins@co.lincoln.or.us,
sdruckenmiller@co.linn.or.us,
countyclerk@malheurco.org,
elections@co.marion.or.us,
bchilders@co.morrow.or.us,
elections@multco.us,
unger.valerie@co.polk.or.us,
percyb@grantcounty-or.gov,
elections@co.hood-river.or.us,
walkercd@jacksoncounty.org,
kathy.marston@co.jefferson.or.us,
clerk@co.josephine.or.us,
KlamathCountyElections@klamathcounty.org,
sgeaney@co.lake.or.us,
elections@co.clackamas.or.us,
Betty.Huser@co.columbia.or.us,
coosclerk@co.coos.or.us,
cc_clerk@co.crook.or.us,
clerk@co.curry.or.us,
elections@deschutes.org,
ellen.wagenaar@co.gilliam.or.us,
stories@ktvz.com,
info@zolomedia.com

Email I sent

To whom it may concern,

There is a startling conflict of interest in using Smartmatic voting machines and growing concern that our election will be manipulated.  I am writing to request that Oregon counties invoke their conflict of interest clause in voting machine contracts and fall back to a method alternate to Smartmatic.

Wikileaks has proven beyond a doubt that George Soros is backing the democrats and one of his companies produces Smartmatic machines.

Smartmatic has been suspected in rigging elections in other countries which can be found in this 1.4(b) classified leaked document from Wikileaks.

Please provide a fair election.

**Comment by HelloKitty** [comment]
Hi, in about 8 hours when I become free again and I'll start aggregating the emails into the data. That way people can both call and/or email.

Thank you very much for your work!

**Comment by Dutchgirlie48** [comment]
Hi, I'm going to start to find e-mails now.

**Comment by Dutchgirlie48** [comment]
mail addresses for most Oregon county election boards (please complete) and ktvz/zolo media:

countyclerk@shermancounty.net, 1-541-565-3606
clerk@co.tillamook.or.us, 1-503-842-3402
elections@umatillacounty.net, 1-541-278-6254
rchurch@union-county.org, 1-541-963-1006
lindab@co.wasco.or.us, 1-541-506-2530
elections@co.washington.or.us,  1-503-846-5800
bsitton@co.wheeler.or.us, 1-541-763-2400
elections@co.yamhill.or.us, 1-503-434-7518
elections.customer@co.lane.or.us,  1-541-682-4234
djenkins@co.lincoln.or.us, 1-541-265-4131
sdruckenmiller@co.linn.or.us, 1-541-967-3831
countyclerk@malheurco.org, 1-541-473-5151
elections@co.marion.or.us,  1-503-588-5041 or 800-655-5388
bchilders@co.morrow.or.us, 1-541-676-5604
elections@multco.us, 1-503-988-3720
unger.valerie@co.polk.or.us, 1-503-623-9217
percyb@grantcounty-or.gov,  1-541-575-1675
elections@co.hood-river.or.us,  1-541-386-1442
walkercd@jacksoncounty.org, 1-541-774-6148
kathy.marston@co.jefferson.or.us, 1-541-475-4451
clerk@co.josephine.or.us, 1-541-474-5240
KlamathCountyElections@klamathcounty.org, 1-541-883-5134
sgeaney@co.lake.or.us, 1-541-947-0905
elections@co.clackamas.or.us,  1-503-655-8510
Betty.Huser@co.columbia.or.us, 1-503-397-7214 or 503-397-3796
coosclerk@co.coos.or.us, 1-541-396-7610
cc_clerk@co.crook.or.us,1-541-447-6553
clerk@co.curry.or.us, 1-541-247-3297 or 1-877-739-4218
elections@deschutes.org, 1-541-388-6547
ellen.wagenaar@co.gilliam.or.us, 1-541-384-2311
stories@ktvz.com,  1-541-617-6223
info@zolomedia.com 1-541-749-5151

**Comment by usersex** [comment]
I'll do a PR for you

**Comment by usersex** [comment]
Included in https://github.com/HelloKitty/AmericansStopSoros/pull/8/commits

**Comment by usersex** [comment]
@HelloKitty, I included the emails in a PR -  https://github.com/HelloKitty/AmericansStopSoros/pull/8

**Comment by h3xxya** [comment]
According to a reply from Marion county, no Oregon county uses Smartmatic voting machines:

Good morning 

The Marion County Clerk's office in Oregon does not use Smartmatic voting systems. Furthermore, even if we did, we would code or program our own elections to assure accurate counts. Oregon is an innovative vote-by-mail state. Therefore we have a paper trail allowing ballots to be verified and recounted by hand if there is any question. Also with our signature verification and election management, we accept for opening only one ballot from only eligible voters.  No Oregon county uses Smartmatic. 

Come on by and see our process. We will demonstrate Tuesday morning, November 1.

Thanks for your interest.

Bill Burgess
Marion County Clerk

**Comment by josephplattenberger** [comment]
Good job. Now by Smartmatics own submission they have revealed none of their technology with be used for the upcoming 2016 US election: http://www.smartmatic.com/case-studies/article/facts-about-smartmatic/
However, Dominion Voting and H.I.G. Capital (Hart Intercivic) are two other voting machine companies which were revealed thru the Guciffer 2.0 hacks to have made substantial donations to the Clinton Foundation. We must demand that these machines either produce paper trails or paper ballots must be provided.

**Comment by HelloKitty** [comment]
@h3xxya You should include questions about Sequoia as their are/were subsidiary of Smartmatic.

God work though, I'd love to add it but you deserve credit for this. Please make a PR with the comment file.

**Comment by h3xxya** [comment]
Further confirmation - we are a vote by mail **only** state.  We only make special exceptions in rare cases.
